# Generated by Django 2.2.14 on 2020-11-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201026_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(default='asd', upload_to=''),
            preserve_default=False,
        ),
    ]
